name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  
  #dateFormat
  intl: ^0.18.1

  #Database (eliminado Floor)

  #make request to api
  retrofit: ^4.7.1

  # Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.5
  firebase_auth: ^4.15.0


  #Hooks
  flutter_hooks: ^0.18.3

  #chached image 
  cached_network_image: ^3.2.0
  typed_data: ^1.4.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.6
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

dependency_overrides:
  win32: ^5.14.0
  typed_data: ^1.4.0
  path_provider_android: ^2.2.17
  sqflite: ^2.4.2
